# Generated by Django 4.2 on 2023-05-08 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SWEETSHIRT', 'Свитшоты'), ('COAT', 'Пальто'), ('SWIMSUIT', 'Купальники'), ('CARDIGAN', 'Кардиганы'), ('T_SHIRT', 'Футболки'), ('HOODY', 'Худи'), ('NEW_CATEGORY', 'Новая категория')], default='coat', max_length=20)),
                ('slug', models.SlugField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BROWN', 'Коричневый'), ('WHITE', 'Белый'), ('PINK', 'Розовый'), ('ORANGE', 'Оранжевый')], default='brown', max_length=6)),
                ('slug', models.SlugField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='s', max_length=4)),
                ('slug', models.SlugField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('cover', models.ImageField(upload_to='', verbose_name='Фото')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, max_length=5, null=True, verbose_name='Цена')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Процент скидки')),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=5, max_length=5, null=True, verbose_name='Цена со скидкой')),
                ('slug', models.SlugField(default='', max_length=150)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.category', verbose_name='Категория')),
                ('color', models.ManyToManyField(to='shop.color', verbose_name='Цвет')),
                ('size', models.ManyToManyField(to='shop.size', verbose_name='Размер')),
            ],
        ),
    ]
