# Generated by Django 4.2 on 2023-06-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('SUMMER', 'Лето'), ('AUTUMN', 'Осень'), ('SPRING', 'весна'), ('NEW', 'Новинки'), ('NEW_CATEGORY', 'Новая категория')], default='coat', max_length=20),
        ),
    ]
