# Generated by Django 4.2 on 2023-10-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_category_name_alter_color_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Процент скидки'),
        ),
    ]
